name: Pull Request Creation

on:
  push:
    branches:
      - main

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_pull_requests
        with:
          query: |
            query pullRequest($repo: String!, $owner: String!) {
              repository(name: $repo, owner: $owner) {
                    pullRequests(last: 100, orderBy: {field: CREATED_AT, direction: DESC}) {
                      totalCount
                      nodes {
                        title
                        url
                        state
                        createdAt
                      }
                      pageInfo {
                        hasNextPage
                        endCursor
                      }
                    }
                }
              }
          variables: |
            {
              "repo": "${{ github.event.repository.name }}",
              "owner": "${{ github.event.repository.owner.login }}"
            }
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}