name: Pull Request Creation

on:
  push:
    branches:
      - main

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_pull_requests
        with:
          query: |
            query user(owner: "Sherida101", name: "Portfolio") {
              pullRequests(last: 100, orderBy: {field: CREATED_AT, direction: DESC}) {
                totalCount
                nodes {
                  title
                  url
                  state
                  createdAt
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}